export const games = {
  title: "Desenvolvedor de Jogos Unity C# (Autônomo)",
  period: "01/2020 - 09/2022",
  location: "São Paulo, SP - Brasil",
  description:
    "Desenvolvi projetos e serviços para diversas empresas como profissional autônomo.",
  topics: [
    "Desenvolvi 17 jogos (autorais e para terceiros) com a Unity, que foram publicados e tiveram mais de 10.000 vendas, sendo reconhecido pela revista Warpzone.",
    "Redigi 118 artigos para o site Crie Seus Jogos, que impulsionou o site e a divulgação de cursos sobre desenvolvimento de jogos por meio da otimização via SEO.",
  ],
  others: [
    "TypeScript",
    "Next",
    "Expo",
    "Styled Components",
    "Chakra UI",
    "TanStack Query",
    "Zustand",
    "React Hook Form",
    "Zod",
    "Docker",
    "Express",
    "Sequelize",
    "Nest",
    "Prisma",
    "Redis",
    "Firebase",
    "OneSignal",
    "AWS (EC2 e S3)",
    "Vercel",
    "Railway",
    "Figma",
  ],
};
